name: Python CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests and generate JUnit XML report
      run: |
        pytest --maxfail=5 --disable-warnings --junitxml=pytest-report.xml

    - name: Cache SonarQube Scanner
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.py') }}

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v3
      env:
          SONAR_SCANNER_OPTS: "-X"
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
        additional_args: >
          -Dsonar.junit.reportPaths=pytest-report.xml

    # Upload test results as artifact
    - name: Upload test result as artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: pytest-report.xml
